; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino

; dependencias de librerías para sensor y pantalla
lib_deps =
    mikalhart/NewPing@^1.9.1 ; biblioteca para sensor ultrasónico HC-SR04
    johnrickman/LiquidCrystal_I2C@^1.1.2 ; pantalla LCD I2C 16x2
